export const indoorItems = [
  {
    id: 1,
    text: "CAMERA INTERNA PTZ 1",
    image: "/devices/indoor/camIn1_1.webp",
    imageWhite: "/devices/indoor/camIn1_2.webp",
    realImage: "/devices/realIndoor/camIn1_2.webp",
    actionImage: "/pov/inside/living_panoramic.webp",
    description:
      "Câmera móvel com rotação de 360 graus. Cubra todos os ângulos sem pontos cegos.",
    specs: [
      "Câmera 360°",
      "Zoom de 4x",
      "Rastreamento de movimento Automático",
      "Áudio Bidirecional",
    ],
  },
  {
    id: 2,
    text: "CAMERA INTERNA PTZ 2",
    image: "/devices/indoor/camIn2_1.webp",
    imageWhite: "/devices/indoor/camIn2_2.webp",
    realImage: "/devices/realIndoor/camIn2_2.webp",
    actionImage: "/pov/inside/panoramic_bedroom.webp",
    description:
      "Câmera móvel com rotação de 360 graus. Cubra todos os ângulos sem pontos cegos",
    specs: [
      "Áudio Bidirecional",
      "Detecção de movimento",
      "Integração via Wi-fi",
      "Conectividade Tuya",
    ],
  },
  {
    id: 3,
    text: "CAMERA INTERNA FIXA 1",
    image: "/devices/indoor/camIn3_1.webp",
    imageWhite: "/devices/indoor/camIn3_2.webp",
    realImage: "/devices/realIndoor/camIn3_2.webp",
    actionImage: "/pov/inside/baby_room.webp",
    description: "Câmera interna com design minimalista fixa",
    specs: [
      "Áudio Bidirecional",
      "Zoom Óptico 4x",
      "Detecção de movimento",
      "Integração via Wi-fi",
    ],
  },
  {
    id: 4,
    text: "CAMERA INTERNA FIXA 2",
    image: "/devices/indoor/camIn4_1.webp",
    imageWhite: "/devices/indoor/camIn4_2.webp",
    realImage: "/devices/realIndoor/camIn4_2.webp",
    actionImage: "/pov/inside/living_room.webp",
    description: "Câmera interna fixa",
    specs: [
      "Áudio Bidirecional",
      "Zoom Óptico 4x",
      "Detecção de movimento",
      "Integração via Wi-fi",
    ],
  },
  {
    id: 5,
    text: "SENSOR MAGNÉTICO",
    image: "/devices/indoor/doorMoveDetc_1.webp",
    imageWhite: "/devices/indoor/doorMoveDetc_2.webp",
    realImage: "/devices/realIndoor/doorMoveDetc_2.webp",
    description: "Sensor infravermelho passivo de alta sensibilidade",
    specs: [
      "Reporta aberturas e fechamentos",
      "4 níveis de volume",
      "Baixo consumo durante operação",
      "Bateria DC 3V",
    ],
  },
  {
    id: 6,
    text: "OLHO MÁGICO INTELIGENTE",
    image: "/devices/indoor/olhoMagico_1.webp",
    imageWhite: "/devices/indoor/olhoMagico_2.webp",
    realImage: "/devices/realIndoor/olhoMagico_2.webp",
    actionImage: "/pov/inside/deliver.gif",
    description: "Segurança sem fio e áudio bidirecional",
    specs: [
      "Visão Ultra-Wide 150°",
      "Áudio bidirecional com detecção humana",
      "Movimento inteligente",
    ],
  },
  {
    id: 7,
    text: "SENSOR DE MOVIMENTO",
    image: "/devices/indoor/sensorMovimento_1.webp",
    imageWhite: "/devices/indoor/sensorMovimento_2.webp",
    realImage: "/devices/realIndoor/sensorMovimento_2.webp",
    description: "Detecta movimento instantaneamente",
    specs: [
      "Conectividade de 2.4GHz",
      "Detecção de movimento de alta sensibilidade",
      "Alimentação 100~240V",
    ],
  },
  {
    id: 8,
    text: "SIRENE ESTROBOSCÓPICA",
    image: "/devices/indoor/sirene1_1.webp",
    imageWhite: "/devices/indoor/sirene1_2.webp",
    realImage: "/devices/realIndoor/sirene1_2.webp",
    description: "Alarme sonoro e visual de alta intensidade",
    specs: ["Nível sonoro de 85dB", "Suporta até 50 sensores sem fio"],
  },
  {
    id: 9,
    text: "VIDEO PORTEIRO INTERNO",
    image: "/devices/indoor/videoPorteiroFora_1.webp",
    imageWhite: "/devices/indoor/videoPorteiroFora_2.webp",
    realImage: "/devices/realIndoor/videoPorteiroFora_2.webp",
    actionImage: "/pov/inside/videoPorteiro.webp",
    description: "Solução premium de controle total de acesso",
    specs: [
      "Video HD de Alta Definição",
      "Ângulo de visão de 140°",
      "Audio Bidirecional",
      "Sensor de movimento integrado",
    ],
  },
];
